---
- name: Update Nginx loadbalancer configuration
  template:
      src: "templates/loadbalancer.j2"
      dest: /etc/nginx/sites-available/default     
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes